### ISSUE TITLE
After commenting scaling doesn't account for curved display

### ISSUE THREAD

**Issue by ChronicledMonocle** [aeharding/voyager#2183]
**Describe the bug**
With displays that have curved edges (I have a Moto Edge 2024), after a comment, Voyager incorrectly scales down the app window to be within the screen's non-edges. This wasn't a problem until an update or two ago. 

**To Reproduce**

1. Open a topic/thread
2. Make a comment
3. When the comments section reloads, the app window will "shrink down" to the incorrect scaling

The only way to resolve this is to close and reopen Voyager. 

**Expected behavior**
Scaling should account for screen edges. 

**Screenshots**

Correct state prior to commenting:
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/40f992d3-365c-4e80-bcc2-24bf23d74722" />

Incorrect state post commenting:
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/cd9978d4-bfff-4be6-b5fd-d51e22ced43f" />

**Smartphone (please complete the following information):**

- Device: Moto Edge 2024
- OS: Android 15
- Running Native Voyager from F-Droid
- Version 2.41.0

**Comment by aeharding** [comment]
Hi! Thanks for the issue. I've heard of reports of this but I've never been able to reproduce on all the different android devices I have.

If any developer can reproduce and take a shot at fixing I'd appreciate it!

**Comment by ChronicledMonocle** [comment]
> Hi! Thanks for the issue. I've heard of reports of this but I've never been able to reproduce on all the different android devices I have.
> 
> If any developer can reproduce and take a shot at fixing I'd appreciate it!

Thanks for looking! If there are any logs I can provide to help narrow this down or a debug build, I'd be happy to run it on my device and reproduce it. Or I can send a video of the behavior. Whatever is needed. 

I am not a developer, but I am comfortable around adb and Linux commands. 

This happens every single time I comment on my device, so it's easy to reproduce for me.

**Comment by aeharding** [comment]
Oh great, if you can try the beta, there was an attempt at a fix but I heard one user report that didn't work.

Otherwise if you can try installing the APK manually for each previous release and see when it stopped working exactly that would be very helpful.

Also, it always happens EVERY time? Have you tried rebooting your device? Most people that have reached out said it's intermittent, or goes away after rebooting, etc.

**Comment by aeharding** [comment]
Oh and a workaround is to use the Android theme. Although I know some people prefer to the iOS theme!

**Comment by ChronicledMonocle** [comment]
> Oh great, if you can try the beta, there was an attempt at a fix but I heard one user report that didn't work.
> 
> Otherwise if you can try installing the APK manually for each previous release and see when it stopped working exactly that would be very helpful.
> 
> Also, it always happens EVERY time? Have you tried rebooting your device? Most people that have reached out said it's intermittent, or goes away after rebooting, etc.

Where is the latest beta located?  I switched to "Allow betas" in F-Droid, but it didn't present me with anything newer than the stable release.  

I'll try and nail down when the issue started happening version-wise.

It happens every single comment once the problem occurs.  If I reboot my phone, it goes away for a while, but comes back and then it'll be every comment again.  

> Oh and a workaround is to use the Android theme. Although I know some people prefer to the iOS theme!

I can confirm that the Android theme does resolve it.  I can also confirm that switching to the Android theme and then back to the iOS theme makes the problem go away (for now).  I'll update if I can get it to happen again and then start testing prior releases/beta releases.

**Comment by aeharding** [comment]
Ah, that's right, you're using F-droid! The beta is distributed to Google Play Beta and Apple Testflight but not F-droid directly (because it take a week to publish).

For F-droid/FOSS android users, check the build artifacts of the latest commit on the main branch. You should see an APK file.

Try downloading and installing the APK at the bottom of this page for the latest commit on main. I just pushed an attempted fix you can try. https://github.com/aeharding/voyager/actions/runs/20087344439

Try that out for a while (days) and let me know if it fixes it. I know it's quite intermittent so it may take a while to see if the fix actually works.

**Comment by ChronicledMonocle** [comment]
> Ah, that's right, you're using F-droid! The beta is distributed to Google Play Beta and Apple Testflight but not F-droid directly (because it take a week to publish).
> 
> For F-droid/FOSS android users, check the build artifacts of the latest commit on the main branch. You should see an APK file.
> 
> Try downloading and installing the APK at the bottom of this page for the latest commit on main. I just pushed an attempted fix you can try. https://github.com/aeharding/voyager/actions/runs/20087344439
> 
> Try that out for a while (days) and let me know if it fixes it. I know it's quite intermittent so it may take a while to see if the fix actually works.

Awesome.  Thanks!  It looks like it's still building, but once the build job finishes, I'll install the APK and let you know!

[EDIT]

NVM.  The Android build is done.  Just the docker one isn't.  Downloading and installing now!

**Comment by ChronicledMonocle** [comment]
Woke up this morning and reopened the app on the beta build and, sadly, this issue was still present. Switching to the Apple theme and back to Android fixed the scaling until I made another comment. Then it broke again.

**Comment by Stugist** [comment]
I'm getting the same issue.

Phone: Honor Magic V3 fold FCP-N49
Android version: 15
Voyager version: 2.41.0 play store install

**Comment by ChronicledMonocle** [comment]
> I'm getting the same issue.
> 
> Phone: Honor Magic V3 fold FCP-N49 Android version: 15 Voyager version: 2.41.0 play store install

Do you see the same issue on the Android theme?

**Comment by Stugist** [comment]
Don't seem to? But I've only made one comment since switching from iOS theme, and I often get 1-5 comments before it happens.

**Comment by ChronicledMonocle** [comment]
> Don't seem to? But I've only made one comment since switching from iOS theme, and I often get 1-5 comments before it happens.

Gotcha. I only ask because apparently that's a known workaround, if you read earlier in the bug report, so I just wanted to make sure you don't have some other buggy behavior that is related, but with a different mechanism of triggering it.

**Comment by cnovel** [comment]
It's also happening with my Pixel 8a. I was using iOS, now switched to Android. Will update in a few days if issue is still happening.

**Comment by Stugist** [comment]
So far I've not had it happen since switching to the android theme.

**Comment by aeharding** [comment]
Thanks, that is a bummer it didn't fix the problem.

At this point I wonder if its a browser bug, or an Ionic bug. It definitely doesn't happen on iOS Safari, and I also can't replicate on any of my Android devices.

**Comment by aeharding** [comment]
Hi everyone,

I have another attempt deploying now. It might fix the problem but I'm not sure. Please try it out in beta once it deploys!

If that doesn't work, I have a blunt/hack workaround (https://github.com/aeharding/voyager/pull/2192), but ideally I'd like to fix the underlying problem if possible.

**Comment by SkaveRat** [comment]
I think this happens because the toast is too wide and the rest of the page resizes to fit it? 

I can reliably recreate it when I write or edit a post. And the toast is wider than the rest of the content

Device is a Pixel 6a

<img width="1080" height="1204" alt="Image" src="https://github.com/user-attachments/assets/2f497c1a-717c-4cb6-9d3e-ddf23ba5aced" />

**Comment by cnovel** [comment]
I've been using the Android theme for the last 3 weeks, no issue, so the workaround seems to be working.

**Comment by scstraus** [comment]
I can't say I've noticed it specifically after editing a new comment, but I've noticed it when Lemmy was the last app I used and my phone locked. Then when I unlocked it again the border was there. This is on iOS.

**Comment by Baliverbes** [comment]
I've had this happen since the latest update that I did two days ago (2.43.1), from Fdroid. I don't have a device with curved edges though, it's a Huawei P30. I haven't been able to figure out the circumstances so far.

**Comment by scstraus** [comment]
It's still happening to me on iOS

**Comment by vext01** [comment]
I have this issue on android.

After posting a comment, the app gets smaller and there's a black border.

Samsung A34 5G. Android 16.

**Comment by aproposnix** [comment]
As of 02.09.2026, it's still an issue. For me it's on the Fairphone 6

**Comment by scstraus** [comment]
I have not noticed this issue any more recently on iOS. Maybe for the last 3-4 months.
