### ISSUE TITLE
Jump to top in Communities

### ISSUE THREAD

**Issue by kerosyn** [aeharding/voyager#382]
Currently when viewing favourites/subscribed communities it does not appear possible to jump to the top of the Communities by pressing the Posts button on the bottom bar.

**Expectation**
Pressing the Posts button should jump to the top of Communities, like it does for posts once viewing All/Home/Local.

Related to issue #92

Running:
iOS 17 Developer Beta 2
Safari 
iPhone 13
Voyager 0.19.0

**Comment by Daneish** [comment]
I can replicate this issue on iOS, iPadOS and Windows 11 (Edge) on Voyager 0.19.0 installed as app.

Has issues:
iPhone 11 Pro, iOS 16.5.1, Safari
iPad Pro 2018, iPadOS 16.5.1, Safari
Dell XPS 13, Windows 11, Edge

**Comment by robertafreese** [comment]
Not sure if this is apolloparity but tapping pretty above the community name in the top bar on both the listing of posts or post detail and comments screens taking you to the top is pretty common on the apps that I am using. Dystopia and Narwhal both implement this. 

Narwhal and Dystopia both seem to have a sweet spot above the community name. 

It's very useful. I can record the behavior if that would be helpful.

**Comment by kerosyn** [comment]
> Not sure if this is apolloparity but tapping pretty above the community name in the top bar on both the listing of posts or post detail and comments screens taking you to the top is pretty common on the apps that I am using. Dystopia and Narwhal both implement this. 

Apollo did have that, clicking right below the notch. What I mentioned I don’t even remember if it was in Apollo, but it to make it so pressing the Post button functions identically both when viewing posts and Communities since both are housed under the same “Posts” view.

It’s always handy to have a way to jump to the top.

**Comment by aeharding** [comment]
This should be resolved in 0.20.0!

**Comment by robertafreese** [comment]
I don't know what I am doing wrong, but this is not working for me on Android or iOS. Tapping at the top of the screen has no effect. I could try to record a session if that would help.

**Comment by rsammelson** [comment]
He meant that if you press the posts button it jumps to the top. Pressing the status bar at the top to jump to the top is unresolved (see #92 I think).

**Comment by aeharding** [comment]
Yep, tapping the status bar will never work for PWAs unless browsers implement an API.

**Comment by rsammelson** [comment]
@aeharding I mentioned this in that other issue, but I still don't understand why it's not possible to do this but it is possible to open the community search when you click the feed status bar.

**Comment by aeharding** [comment]
The tab bar is just HTML in the page that we fully control. But the native OS status bar is fully controlled by the OS - it's an overlay of the HTML page itself - and it's impossible to intercept tap events to it.

**Comment by rsammelson** [comment]
See #418, but my understanding of what others wanted (and what I would like) is just tapping on the title bar to scroll, not necessarily all the way up to the status bar.

**Comment by robertafreese** [comment]
Ah ok, yes I will watch 418 then, thanks. I figured out subscribing and will test as it progresses.
